# Generated by Django 2.2.5 on 2020-12-11 17:43

from django.db import migrations, models
import django.db.models.deletion
import message.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8, null=True)),
                ('document', models.FileField(max_length=10485760, null=True, upload_to=message.models.user_directory_path)),
                ('image', models.ImageField(max_length=5242880, null=True, upload_to=message.models.user_directory_path)),
                ('audio', models.FileField(max_length=5242880, null=True, upload_to=message.models.user_directory_path)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('added_at', models.TimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
